name = "luau"
type = "javascript"
route = 'luau.ml/*'
zone_id = 'b82a2b985d7ea7cf7bb44e05ef490ad2'
usage_model = ''
workers_dev = false

[build]
command = ""

[build.upload]
format = "service-worker"

[site]
bucket = "./build"
entry-point = "./workers-site"
